INSERT INTO CAR (COUNTRY, CREATE_DATE, MANUFACTURE, MODEL, TYPE) VALUES ('USA', '2000-10-10', 'Buick', 'Roadmaster', 'Large');
INSERT INTO CAR (COUNTRY, CREATE_DATE, MANUFACTURE, MODEL, TYPE) VALUES ('USA', '2000-10-10', 'Buick', 'LeSabre', 'Large');
INSERT INTO CAR (COUNTRY, CREATE_DATE, MANUFACTURE, MODEL, TYPE) VALUES ('USA', '2000-10-10', 'Chrysler', 'Imperial', 'Large');
INSERT INTO CAR (COUNTRY, CREATE_DATE, MANUFACTURE, MODEL, TYPE) VALUES ('USA', '2000-10-10', 'Cadillac', 'DeVille', 'Large');